language: node_js
node_js:
  - "8"
cache: yarn
script:
  - echo 'Deploy!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
  - npm run test:prod
install:
  - npm install -g firebase-tools
after_success:
  - npm run build
  - firebase deploy --token "$FIREBASE_TOKEN"
